// Date: 01/10/2018 23:46:04
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX






package com.crowsofwar.avatar.client.render;

import net.minecraft.client.model.ModelBase;
import net.minecraft.client.model.ModelRenderer;
import net.minecraft.entity.Entity;

public class ModelAirBlade extends ModelBase
{
  //fields
    ModelRenderer AirBlade1;
    ModelRenderer AirBladeB1;
    ModelRenderer AirBladeB2;
    ModelRenderer AirBladeB3;
    ModelRenderer AirBladeB4;
    ModelRenderer AirBladeB5;
    ModelRenderer AirBladeC1;
    ModelRenderer AirBladeC2;
    ModelRenderer AirBladeC3;
    ModelRenderer AirBladeC4;
    ModelRenderer AirBladeC5;
  
  public ModelAirBlade()
  {
    textureWidth = 64;
    textureHeight = 32;
    
      AirBlade1 = new ModelRenderer(this, 0, 0);
      AirBlade1.addBox(-4F, -0.5F, 0F, 8, 1, 5);
      AirBlade1.setRotationPoint(0F, 10F, -0.8F);
      AirBlade1.setTextureSize(64, 32);
      AirBlade1.mirror = true;
      setRotation(AirBlade1, 0F, 0F, 0F);
      AirBladeB1 = new ModelRenderer(this, 0, 7);
      AirBladeB1.addBox(-3F, -0.5F, 0F, 3, 1, 5);
      AirBladeB1.setRotationPoint(-4F, 10F, -0.8F);
      AirBladeB1.setTextureSize(64, 32);
      AirBladeB1.mirror = true;
      setRotation(AirBladeB1, 0F, 0.3490659F, 0F);
      AirBladeB2 = new ModelRenderer(this, 0, 14);
      AirBladeB2.addBox(-3F, -0.5F, 0F, 3, 1, 4);
      AirBladeB2.setRotationPoint(-6.7F, 10F, 0.2F);
      AirBladeB2.setTextureSize(64, 32);
      AirBladeB2.mirror = true;
      setRotation(AirBladeB2, 0F, 0.4363323F, 0F);
      AirBladeB3 = new ModelRenderer(this, 0, 20);
      AirBladeB3.addBox(-3F, -0.5F, 0F, 3, 1, 3);
      AirBladeB3.setRotationPoint(-9.4F, 10F, 1.5F);
      AirBladeB3.setTextureSize(64, 32);
      AirBladeB3.mirror = true;
      setRotation(AirBladeB3, 0F, 0.6108652F, 0F);
      AirBladeB4 = new ModelRenderer(this, 0, 25);
      AirBladeB4.addBox(-2F, -0.5F, 0F, 2, 1, 2);
      AirBladeB4.setRotationPoint(-11.8F, 10F, 3.2F);
      AirBladeB4.setTextureSize(64, 32);
      AirBladeB4.mirror = true;
      setRotation(AirBladeB4, 0F, 0.9599311F, 0F);
      AirBladeB5 = new ModelRenderer(this, 0, 29);
      AirBladeB5.addBox(-1F, -0.5F, 0F, 1, 1, 1);
      AirBladeB5.setRotationPoint(-12.9F, 10F, 4.8F);
      AirBladeB5.setTextureSize(64, 32);
      AirBladeB5.mirror = true;
      setRotation(AirBladeB5, 0F, 1.047198F, 0F);
      AirBladeC1 = new ModelRenderer(this, 19, 7);
      AirBladeC1.addBox(0F, -0.5F, 0F, 3, 1, 5);
      AirBladeC1.setRotationPoint(4F, 10F, -0.8F);
      AirBladeC1.setTextureSize(64, 32);
      AirBladeC1.mirror = true;
      setRotation(AirBladeC1, 0F, -0.3490659F, 0F);
      AirBladeC2 = new ModelRenderer(this, 19, 14);
      AirBladeC2.addBox(0F, -0.5F, 0F, 3, 1, 4);
      AirBladeC2.setRotationPoint(6.7F, 10F, 0.2F);
      AirBladeC2.setTextureSize(64, 32);
      AirBladeC2.mirror = true;
      setRotation(AirBladeC2, 0F, -0.4363323F, 0F);
      AirBladeC3 = new ModelRenderer(this, 19, 20);
      AirBladeC3.addBox(0F, -0.5F, 0F, 3, 1, 3);
      AirBladeC3.setRotationPoint(9.4F, 10F, 1.5F);
      AirBladeC3.setTextureSize(64, 32);
      AirBladeC3.mirror = true;
      setRotation(AirBladeC3, 0F, -0.6108652F, 0F);
      AirBladeC4 = new ModelRenderer(this, 19, 25);
      AirBladeC4.addBox(0F, -0.5F, 0F, 2, 1, 2);
      AirBladeC4.setRotationPoint(11.8F, 10F, 3.2F);
      AirBladeC4.setTextureSize(64, 32);
      AirBladeC4.mirror = true;
      setRotation(AirBladeC4, 0F, -0.9599311F, 0F);
      AirBladeC5 = new ModelRenderer(this, 19, 29);
      AirBladeC5.addBox(0F, -0.5F, 0F, 1, 1, 1);
      AirBladeC5.setRotationPoint(12.9F, 10F, 4.8F);
      AirBladeC5.setTextureSize(64, 32);
      AirBladeC5.mirror = true;
      setRotation(AirBladeC5, 0F, -1.047198F, 0F);
  }
  
  public void render(Entity entity, float f, float f1, float f2, float f3, float f4, float f5)
  {
    super.render(entity, f, f1, f2, f3, f4, f5);
    setRotationAngles(f, f1, f2, f3, f4, f5, entity);
    AirBlade1.render(f5);
    AirBladeB1.render(f5);
    AirBladeB2.render(f5);
    AirBladeB3.render(f5);
    AirBladeB4.render(f5);
    AirBladeB5.render(f5);
    AirBladeC1.render(f5);
    AirBladeC2.render(f5);
    AirBladeC3.render(f5);
    AirBladeC4.render(f5);
    AirBladeC5.render(f5);
  }
  
  private void setRotation(ModelRenderer model, float x, float y, float z)
  {
    model.rotateAngleX = x;
    model.rotateAngleY = y;
    model.rotateAngleZ = z;
  }
  
  public void setRotationAngles(float f, float f1, float f2, float f3, float f4, float f5, Entity entity)
  {
    super.setRotationAngles(f, f1, f2, f3, f4, f5, entity);
  }

}
