// Date: 20.05.2017 23:22:05
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX

package com.crowsofwar.avatar.client.render;

import net.minecraft.client.model.ModelBase;
import net.minecraft.client.model.ModelRenderer;
import net.minecraft.entity.Entity;

public class ModelOtterpenguin extends ModelBase {
	// fields
	ModelRenderer tail_2;
	ModelRenderer tail_1;
	ModelRenderer body;
	ModelRenderer Piece_right_arms;
	ModelRenderer Piece_left_arms;
	ModelRenderer Head_Piece;
	ModelRenderer R_foot_piece;
	ModelRenderer L_foot_piece;
	
	public ModelOtterpenguin()
  {
    textureWidth = 128;
    textureHeight = 64;
    
      tail_2 = new ModelRenderer(this, 40, 34);
      tail_2.addBox(-2.5F, 3F, -2.8F, 5, 6, 1);
      tail_2.setRotationPoint(0F, 18F, 4F);
      tail_2.setTextureSize(128, 64);
      tail_2.mirror = true;
      setRotation(tail_2, 1.099557F, 0F, 0F);
      tail_1 = new ModelRenderer(this, 54, 33);
      tail_1.addBox(-3F, -3F, -1F, 6, 7, 2);
      tail_1.setRotationPoint(0F, 18F, 4F);
      tail_1.setTextureSize(128, 64);
      tail_1.mirror = true;
      setRotation(tail_1, 0.3839724F, 0F, 0F);
      body = new ModelRenderer(this, 1, 29);
      body.addBox(-4F, 0F, -3F, 8, 12, 7);
      body.setRotationPoint(0F, 7F, 0F);
      body.setTextureSize(128, 64);
      body.mirror = true;
      setRotation(body, 0F, 0F, 0F);
    Piece_right_arms = new ModelRenderer(this, "Piece_right_arms");
    Piece_right_arms.setRotationPoint(-4F, 7F, 0F);
    setRotation(Piece_right_arms, 0F, 0F, 0F);
    Piece_right_arms.mirror = true;
      right_arm_1 = new ModelRenderer(this, 73, 0);
      right_arm_1.addBox(-1.5F, 4F, -3F, 1, 10, 4);
      right_arm_1.setRotationPoint(1F, 0F, 1F);
      right_arm_1.setTextureSize(128, 64);
      right_arm_1.mirror = true;
      setRotation(right_arm_1, 0F, 0F, 0.0349066F);
      right_arm_2 = new ModelRenderer(this, 73, 0);
      right_arm_2.addBox(-1.8F, 0F, -3F, 1, 10, 4);
      right_arm_2.setRotationPoint(2F, 1F, 1F);
      right_arm_2.setTextureSize(128, 64);
      right_arm_2.mirror = true;
      setRotation(right_arm_2, 0F, 0F, 0.1570796F);
      ModelOtterPenguin.addChildModelRenderer(Piece_right_arms);
    Piece_left_arms = new ModelRenderer(this, "Piece_left_arms");
    Piece_left_arms.setRotationPoint(4F, 7F, 0F);
    setRotation(Piece_left_arms, 0F, 0F, 0F);
    Piece_left_arms.mirror = true;
      left_arm_1 = new ModelRenderer(this, 85, 0);
      left_arm_1.addBox(0.8F, 0F, -3F, 1, 10, 4);
      left_arm_1.setRotationPoint(-2F, 1F, 1F);
      left_arm_1.setTextureSize(128, 64);
      left_arm_1.mirror = true;
      setRotation(left_arm_1, 0F, 0F, -0.1570796F);
      left_arm_2.mirror = true;
      left_arm_2 = new ModelRenderer(this, 73, 0);
      left_arm_2.addBox(0.5F, 4F, -3F, 1, 10, 4);
      left_arm_2.setRotationPoint(-1F, 0F, 1F);
      left_arm_2.setTextureSize(128, 64);
      left_arm_2.mirror = true;
      setRotation(left_arm_2, 0F, 0F, -0.0349066F);
      left_arm_2.mirror = false;
      ModelOtterPenguin.addChildModelRenderer(Piece_left_arms);
    Head_Piece = new ModelRenderer(this, "Head_Piece");
    Head_Piece.setRotationPoint(0F, 7F, 0F);
    setRotation(Head_Piece, 0F, 0F, 0F);
    Head_Piece.mirror = true;
      Head Piece.addBox("nose", -1F, -3F, -4F, 2, 1, 1);
      Head Piece.addBox("beard 2", -2F, -1,6F, -3,6F, 1, 3, 0);
      Head Piece.addBox("beard 1", 1F, -1,6F, -3,6F, 1, 3, 0);
      Head Piece.addBox("head", -4F, -8F, -3,5F, 8, 8, 8);
      ModelOtterPenguin.addChildModelRenderer(Head_Piece);
    R_foot_piece = new ModelRenderer(this, "R_foot_piece");
    R_foot_piece.setRotationPoint(-2F, 19F, 0F);
    setRotation(R_foot_piece, 0F, 0F, 0F);
    R_foot_piece.mirror = true;
      R foot piece.addBox("right shin", -1F, 2F, -1F, 2, 2, 2);
      R foot piece.addBox("right leg", -2F, 0F, -2F, 4, 2, 4);
      R foot piece.addBox("right foot", -1,5F, 4F, -3F, 3, 1, 4);
      ModelOtterPenguin.addChildModelRenderer(R_foot_piece);
    L_foot_piece = new ModelRenderer(this, "L_foot_piece");
    L_foot_piece.setRotationPoint(2F, 19F, 0F);
    setRotation(L_foot_piece, 0F, 0F, 0F);
    L_foot_piece.mirror = true;
      L foot piece.addBox("left leg", -2F, 0F, -2F, 4, 2, 4);
      L foot piece.addBox("left foot", -1,5F, 4F, -3F, 3, 1, 4);
      L foot piece.addBox("left shin", -1F, 2F, -1F, 2, 2, 2);
      ModelOtterPenguin.addChildModelRenderer(L_foot_piece);
  }
	
	public void render(Entity entity, float f, float f1, float f2, float f3, float f4, float f5) {
		super.render(entity, f, f1, f2, f3, f4, f5);
		setRotationAngles(f, f1, f2, f3, f4, f5);
		tail_2.render(f5);
		tail_1.render(f5);
		body.render(f5);
		Piece_right_arms.render(f5);
		Piece_left_arms.render(f5);
		Head_Piece.render(f5);
		R_foot_piece.render(f5);
		L_foot_piece.render(f5);
	}
	
	private void setRotation(ModelRenderer model, float x, float y, float z) {
		model.rotateAngleX = x;
		model.rotateAngleY = y;
		model.rotateAngleZ = z;
	}
	
	public void setRotationAngles(float f, float f1, float f2, float f3, float f4, float f5) {
		super.setRotationAngles(f, f1, f2, f3, f4, f5);
	}
	
}
