name: Build

on: [push, pull_request]

jobs:
  build:
    name: Build the code
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew build
    - name: Archive code coverage results
      uses: actions/upload-artifact@v2
      with:
        name: artifact
        path: |
          build/libs
          !build/libs/*-sources.jar
  notify:
    name: Discord notification
    runs-on: ubuntu-latest
    needs:
      - build
    if: ${{ always() }}
    
    steps:
      - name: Notify
        uses: nobrayner/discord-webhook@v1
        with:
          github-token: ${{ secrets.github_token }}
          discord-webhook: ${{ secrets.CI_WEBHOOK_URL }}
